spring:
  application:
    name: getauthor11
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore
    username: kiwi
    password: kiwi01
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 5MB
server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # 指向Eureka Server的URL
    register-with-eureka: true                    # 启用服务注册
    fetch-registry: true                          # 从Eureka拉取注册信息
  instance:
    appname: GETAUTHOR11

logging:
  level:
    org:
      springframework: INFO
      hibernate: INFO
    com:
      kiwi: DEBUG