spring:
  application:
    name: unigpt
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore
    username: kiwi
    password: kiwi01
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
cos:
  secretId: AKIDjKhrCQTVdtvhDTUSYkpfFafXRiATWbgg
  secretKey: DPadT5kFWZTIBC5xeDe5e8e8PSJwaBal
  region: ap-shanghai
  bucketName: web-data-1319894912
