spring:
  application:
    name: bookstore
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore
    username: 
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 5MB
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    timeout: 10s
    
cos:
  secretId: 
  secretKey: 
  region: 
  bucketName: 
