spring:
  application:
    name: unigpt
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore
    username: kiwi
    password: kiwi01
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: kiwi01kiwi #for 8 characters required
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 5MB
  data:
    mongodb:
      uri: mongodb://localhost:27017/BookStore
      username: kiwi
      password: kiwi01
      driver-class-name: org.springframework.data.mongodb.core.MongoTemplate

server:
  port: 8081

cos:
  secretId: AKIDjKhrCQTVdtvhDTUSYkpfFafXRiATWbgg
  secretKey: DPadT5kFWZTIBC5xeDe5e8e8PSJwaBal
  region: ap-shanghai
  bucketName: web-data-1319894912
